os: Windows Server 2012
before_build:
 - nuget restore
 - cmd: "\"C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DAC\\bin\\SqlPackage.exe\" /a:Publish /sf:\"%APPVEYOR_BUILD_FOLDER%\\Database\\SqlServer\\Tracker.dacpac\" /tcs:\"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=EmployeeTimeControlSystem;Integrated Security=True\""
build_script:
 - msbuild EmployeeTimeControl.sln
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.3.1\tools\net452\xunit.console.x86.exe" -targetargs:"Tests\EmployeeTimeControl.Data.Test\bin\Debug\EmployeeTimeControl.Data.Test.dll -noshadow" -filter:"+[*]* -[EmployeeTimeControl.Data.Test]* -[EmployeeTimeControl.Data.Migrations]*" -output:"coverage.xml"
after_test:
 - .\packages\Codecov.1.0.3\tools\codecov.exe -f "coverage.xml"