// <auto-generated />
namespace EmployeeTimeControl.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDayOfWeek_OnDayVisitingRule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDayOfWeek_OnDayVisitingRule));
        
        string IMigrationMetadata.Id
        {
            get { return "201712212031140_AddDayOfWeek_OnDayVisitingRule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
